apiKey: null
artifactDirectory: null
clusterId: null
command: bash pipeline.sh
container: ufoym/deepo:all-py36 # All ML/DL frameworks in a single template with CUDA/cuDNN and other libraries. Python 36.
containerUser: null
experimentEnv: null
ignoreFiles: null
isPreemptible: false
machineType: P5000
modelPath: null
modelType: null
name: train
no-logs: true
ports: null
projectId: pr8w5n77z
registryPassword: null
registryUrl: null
registryUsername: null
tag: null
tags: null
tensorboard: false
tensorboard_set: null
workingDirectory: null
workspace: https://github.com/filipbalucha/know_your_avocado
workspacePassword: null
workspaceRef: null
workspaceUsername: null
